# Site settings

title: Samata Sarma

description: 'Business Card Page'

url: 'http://samsarma.github.io'

baseurl: ''

profilepic: '/images/samlogo.png'

bkimage: '/images/bk1.jpg'

google_analytics: 

font_awesome: 'b08756a215.js'



author:

  name: 'Samata Sarma'

  email: samsarma@gmail.com

  twitter_username: samatasarma

#  facebook_username: joshgerdes

  github_username:  samsarma

# linkedin_username:  thomas-zühlke-889182165

#  meetup_name: Azure-Meetup-Rostock-MV



# Build settings

destination: _site

markdown: kramdown

highlighter: rouge



sass:

    sass_dir: _sass

    style: compressed



kramdown:

  # use Github Flavored Markdown

  input: GFM

  # do not replace newlines by <br>s

  hard_wrap: false



#plugins: ['jekyll-paginate']

exclude: ['README.md', 'screenshot-overview.png']

